### ISSUE TITLE
Open ssh port (22) on gitlab 

### ISSUE THREAD

**Issue by vlalanne** [actiniumio/allspark#40]
### Story
- as a developer, I want to access GIT data over ssh so that I can have a secured connection

---
### Motivation
HTTPS can cause problems with certificates and behind corporate proxy

---
### Acceptance criteria

- [ ] Clone a git repository over ssh
- [ ] Pull a git repository over ssh
- [ ] Push to a git repository over ssh
---

**Comment by Xide** [comment]
Hi,

Thanks for you interest. This feature should indeed be enabled by default. I can't work on it right now, but i'll be available to work on it tomorrow. If you need this before, see with  @guiadco . 

## Request

- `so that I can have a secured connection` -> Connection is secured over HTTPS
-  could you refine the motivation, what are the problems with certificates / corporate proxies you are talking about ? Is it because of the self-signed security alerts ?

## Implementation proposal 
- [ ] Add the `traefik` labels to expose port 22 for `gitlab.{{ allspark_root_domain }}`

**Comment by vlalanne** [comment]
To give a short answer I work in a company where anything that looks like internet access like https and proxies requires extensive validation and authorizations . It is simpler with ssh.

**Comment by guiadco** [comment]
Different issue 
 * https://github.com/containous/traefik/issues/10
 * https://github.com/containous/traefik/issues/1409
 * https://github.com/containous/traefik/issues/1611

**Comment by guiadco** [comment]
Need to investigate to solve the problem.

**Comment by guiadco** [comment]
## Implementation proposal 
- [ ] Try HAProxy to resolve the problem
